name: Release

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Add NuGet Source
      run: dotnet nuget add source --username NowaLone --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/NowaLone/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack NuGet
      run: dotnet pack --configuration Release
    - name: Push
      run: dotnet nuget push src/**.nupkg --source "github"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.GitVersion_SemVer }}
        release_name: v${{ env.GitVersion_SemVer }}
        draft: false
        prerelease: true
